# Generated by Django 4.2.4 on 2023-09-01 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('is_required', models.BooleanField(verbose_name='Is Required?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('is_required', models.BooleanField(verbose_name='Is Required?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NumberQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('is_required', models.BooleanField(verbose_name='Is Required?')),
                ('min_value', models.FloatField(verbose_name='Minimum Value')),
                ('max_value', models.FloatField(verbose_name='Maximum Value')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SingleSelectQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('is_required', models.BooleanField(verbose_name='Is Required?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Survey Name')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Date/Time Created')),
                ('dt_update', models.DateTimeField(auto_now=True, verbose_name='Date/Time Updated')),
                ('slug', models.SlugField(blank=True, default='', verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='TextQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('is_required', models.BooleanField(verbose_name='Is Required?')),
                ('input_length', models.PositiveIntegerField(verbose_name='Text Input Length')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SurveySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.JSONField(verbose_name='Response')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/submitted-images/', verbose_name='Image')),
                ('file', models.FileField(blank=True, null=True, upload_to='media/submitted-files/', verbose_name='File')),
                ('dt_submission', models.DateTimeField(auto_now_add=True, verbose_name='Date/Time Submission')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='survey_app.survey', verbose_name='Survey')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.PositiveIntegerField(verbose_name='Question ID')),
                ('question_content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='Question Content Type')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey_app.survey', verbose_name='Survey')),
            ],
        ),
        migrations.CreateModel(
            name='SingleSelectOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Value')),
                ('select_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='survey_app.singleselectquestion', verbose_name='Single Select Question')),
            ],
        ),
    ]
