# Generated by Django 4.2.4 on 2023-09-03 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveysubmission',
            name='file',
        ),
        migrations.RemoveField(
            model_name='surveysubmission',
            name='image',
        ),
    ]
